# Generated by Django 3.1.6 on 2021-02-05 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_txt',
            new_name='choice_text',
        ),
    ]
