# Generated by Django 3.1.6 on 2021-03-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_details_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='prescription',
            field=models.CharField(default='day - none', max_length=30),
        ),
    ]
