# Generated by Django 3.1.6 on 2021-03-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_doctor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctor',
            new_name='Doctors',
        ),
    ]
