# Generated by Django 3.1.6 on 2021-04-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(default='other', max_length=6),
        ),
    ]
