# Generated by Django 3.1.6 on 2021-04-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_contact_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='age',
            field=models.CharField(default=10, max_length=4),
        ),
    ]
