# Generated by Django 3.1.6 on 2021-04-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_contact_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='doctor',
            field=models.CharField(default='Anish', max_length=40),
        ),
    ]
