# Generated by Django 3.1.6 on 2021-04-05 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_details_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 5, 10, 19, 37, 160356, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.CharField(default='18', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(default='other', max_length=10),
        ),
    ]
