# Generated by Django 3.1.6 on 2021-04-05 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_auto_20210405_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='prescription',
        ),
        migrations.AddField(
            model_name='details',
            name='date_of_visit',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 4, 5, 11, 4, 9, 784249, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='purpose',
            field=models.CharField(default='General Check up', max_length=30),
        ),
    ]
