# Generated by Django 3.1.6 on 2021-04-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_auto_20210405_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='date_of_visit',
            field=models.DateField(auto_now_add=True),
        ),
    ]
