# Generated by Django 3.1.6 on 2021-04-07 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0015_auto_20210405_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(blank=True)),
                ('patient_name', models.CharField(max_length=40)),
                ('doctor_name', models.CharField(max_length=40)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.doctor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
