# Generated by Django 3.1.6 on 2021-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_booking_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slots',
            field=models.CharField(default='', max_length=7),
        ),
    ]
