# Generated by Django 3.1.6 on 2021-04-07 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_doctor_slots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='slots',
        ),
    ]
