# Generated by Django 3.1.6 on 2021-04-08 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='history',
        ),
    ]
