# Generated by Django 3.1.6 on 2021-04-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(max_length=20)),
                ('patient_id', models.CharField(max_length=20)),
                ('doctor_id', models.CharField(max_length=20)),
                ('book_detail', models.CharField(max_length=20)),
            ],
        ),
    ]
