# Generated by Django 3.1.6 on 2021-04-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='age',
        ),
    ]
