# Generated by Django 3.1.6 on 2021-04-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_auto_20210410_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='report_status',
            field=models.BooleanField(default=False),
        ),
    ]
