# Generated by Django 3.1.6 on 2021-04-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_auto_20210410_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.doctor'),
        ),
    ]
