# Generated by Django 3.1.6 on 2021-04-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_auto_20210410_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='lab',
            field=models.CharField(default='General', max_length=40),
        ),
    ]
