# Generated by Django 3.1.6 on 2021-04-10 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_reports_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='book_detail',
        ),
        migrations.AddField(
            model_name='history',
            name='book_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 4, 10, 15, 28, 24, 755553, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='book_slot',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
