# Generated by Django 3.1.6 on 2021-04-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_auto_20210410_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='doctor_name',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='patient_name',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
