# Generated by Django 3.1.6 on 2021-04-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0030_auto_20210410_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
