# Generated by Django 3.1.6 on 2021-04-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0031_auto_20210410_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='reason',
            field=models.CharField(default='--------', max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='book_slot',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
