# Generated by Django 3.1.6 on 2021-04-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0032_auto_20210410_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='book_slot',
            field=models.CharField(max_length=10),
        ),
    ]
