# Generated by Django 3.1.6 on 2021-06-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.IntegerField(unique=True)),
                ('branch', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=5)),
            ],
        ),
    ]
